# Generated by Django 4.2.17 on 2024-12-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='remuneração',
            new_name='remuneracao',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
